INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('Agro Skynet', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('Laboratorio ABC', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('LabCorp', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('LabTech', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('BioLab', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('MedTech', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('LabExpress', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('TechLab Solutions', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('LifeScience Labs', 0);
INSERT INTO laboratorio (nome, quantidade_pessoa) VALUES ('InovaLab', 0);
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda XYZ', '36.627.718/0001-51');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda ABC', '36.627.718/0001-52');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda 123', '36.627.718/0001-53');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Alpha', '36.627.718/0001-54');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Beta', '36.627.718/0001-55');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Gamma', '36.627.718/0001-56');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Delta', '36.627.718/0001-57');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Omega', '36.627.718/0001-58');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Sunrise', '36.627.718/0001-59');
INSERT INTO propriedade (nome, cnpj) VALUES ('Fazenda Sunset', '36.627.718/0001-60');
